config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/", to: "list#home", as: 'root'
  get 'lists', to: "list#list", as: 'all_lists'
  get 'lists/new', to: "list#new", as: "new_list"
  get 'list/:id', to: "list#show", as: 'list'
  post 'lists', to: "list#create"

  # bookmarks
  get 'lists/:id/bookmarks/new', to: 'bookmark#new', as: 'bookmark'
  post 'lists/:id/bookmarks', to: 'bookmark#create', as: 'create_bookmark'
  delete 'bookmarks/:id', to: 'bookmark#destroy', as: 'bookmark_destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "already bookmarked in this list" }
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmark_controller.rb
class BookmarkController < ApplicationController

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to list_path(id: @bookmark.list_id), notice: "Bookmark was created successfully"
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    list_id = @bookmark.list_id
    @bookmark.destroy
    redirect_to list_path(id: list_id), notice: "Bookmark was deleted successfully"
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def home
    @lists = List.all
  end

  def list
    @lists = List.all
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @list_bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: "List was created successfully"
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmark/new.html.erb
<%= simple_form_for @bookmark, url: create_bookmark_path(params[:id]), method: :post do |f| %>
  <%= f.input :list_id, as: :hidden, input_html: { value: params[:id] } %>
  <%= f.input :comment, label: 'comment' %>
  <%= f.association :movie, label_method: :title, value_method: :id, include_blank: false %>
  <%= f.button :submit, 'Create Bookmark' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container">
    <div class="navbar">
      <div class="navbar-left">
        <%= link_to "Movie App", root_path %>
      </div>
      <div class="navbar-right">
        <%= link_to "All Lists", all_lists_path %>
        <%= link_to "New List", new_list_path%>
      </div>
    </div>
      <%= yield %>
  </div>
  </body>
</html>

app/views/list/_index.html.erb
<!---- <ul>
<% @lists.each do |list|%>
  <li><%= link_to list.name, list_path(list) %></li>
<% end %>
</ul>
----!>

<div class="lists">
  <% @lists.each do |list|%>
  <div class="card" style="width: 18rem; border-radius="10px" col-8>
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><%=list.name%></h5>
      <a href="<%= list_path(list) %>" class="btn btn-primary">View List</a>
    </div>
  </div>
  <% end %>
</div>

app/views/list/home.html.erb
<div id="home-splash">
  <div data-controller="type-effect">
    <h1>Keep track of<br>
    your movies
    </h1>
  </div>
  <%= image_tag "cinema.jpg", alt: "cinema", width: 700 %>
</div>
<div class="list-area">
  <div id="lists">
    <h4> Our Lists </h4>
    <%= render 'index' %>
  </div>
</div>

app/views/list/list.html.erb
<div class="list-area">
  <%= render 'index' %>
</div>

app/views/list/new.html.erb
<div class="new-form">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name, label: 'List Name' %>
    <%= f.button :submit, 'Create List' %>
  <% end %>
</div>

app/views/list/show.html.erb
<div class="show-container">
  <div id="back-button"><%= link_to "Back to all lists", lists_path %></div>

  <div class="bookmark-layout">
    <div class="bookmark-header">
      <h1><%= @list.name %></h1>
      <div class="bookmark-btn">
        <%= link_to "Add bookmark", bookmark_path(@list)%>
      </div>
    </div>
    <hr class="solid">
    <ul>
      <div class="bookmarks">
        <% @list_bookmarks.each do |bookmark| %>

        <div class="bookmark">

            <li>
              <div id="bookmark-header">
                <h4><%= bookmark.movie.title %> | <%= bookmark.movie.rating %>★</h4>
                <div id="bookmark-delete">
                  <%= link_to "Delete",
                    bookmark_destroy_path(bookmark),
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
                    %>
                </div>
              </div>

            <p><%= bookmark.comment %><br></p>
          </li>
        </div>

      <% end %>
      </div>
    </ul>


  </div>
</div>